### ISSUE TITLE
Error when trying to move non-active records

### ISSUE THREAD

**Issue by cfharp** [bcolpaert/Colso.Xrm.DataTransporter#1] opened 2016-08-03 23:02 UTC
After some debugging, I was able to track it down to non-active records. Since the exception isn't being handled properly, it comes back as "The record you tried to transfer already exists but you don't have read access to it..." but in my scenario the record is actually inactive. My actual error message is "2 is not a valid status code for state code ..."

**Comment by bcolpaert** [comment] 2016-08-04 07:43
I have reproduced the issue. This is because you are transferring the statecode/statuscode attribute as well. CRM doesn't allow this field to be changed with a create/update. 
I will fix this issue in the next release by executing a SetState request instead of an update of the  statecode/statuscode attributes.

**Comment by bcolpaert** [comment] 2016-10-05 09:57
This issue should be resolved in the latest version

**Closed by bcolpaert** 2016-10-05 09:57 UTC

**Comment by nzhome** [comment] 2017-03-06 00:21
seems this issue hasn't been fixed?  the statecode/statuscode attributes are not available to Checkbox to true, in the list of attributes.
