### ISSUE TITLE
DataTransponter Mapping List error 

### ISSUE THREAD

**Issue by Pakhren88** [bcolpaert/Colso.Xrm.DataTransporter#10] opened 2017-06-15 10:56 UTC
When opening Mapping List window I see error System.ArgumentException
image
![image](https://user-images.githubusercontent.com/19982541/27178311-6e7ca4ea-51d2-11e7-8adc-3b06a178f796.png)

**Comment by bcolpaert** [comment] 2018-03-15 13:26
I could not reproduce this issue, but I assume it is a corrupt settings file. Before opening the tool, try to remove the settings file located at: %AppData%\MscrmTools\XrmToolBox\Settings\Colso.Xrm.DataTransporter.xml

**Comment by duck-o-saurus** [comment] 2018-07-10 14:14
I can confirm this error, too. Removing the settings file didn't solve the problem.
on XRMToolBox v.1.2018.6.25
and Data Transporter v.1.2018.4.1

**Comment by skoopman88** [comment] 2018-07-12 12:13
I can also confirm this message. The workaround is delete anything you've put in your filter to filter your entities for which you want to transfer data from. Then hit Mapping again, it works 👍 

Other BUG i've got is that association transfer won't work with the mapping i've done. Someone help me please. 
on XRMToolBox v.1.2018.6.25
and Data Transporter v.1.2018.4.1

**Comment by duck-o-saurus** [comment] 2018-07-16 01:00
I did a complete uninstall of XRMToolBox and it's Plugins (incl. all configs).
After reinstalling the new version of XRMToolBox v.1.2018.7.26 this problem is gone for me.

Note: Other than skoopman88 i had no input in my filters, so a filter-cleanup didn't solve the problem for me.

**Comment by duck-o-saurus** [comment] 2018-08-02 10:06
Since this bug reappeared for me from time to time, i tried to find out when and by now i can reproduce this error:
After a fresh restart of XRMToolBox and Data Transporter the error seems to be gone. I can normally use the mapping-feature.
But after the first use of the feature "Transfer Data" this error pops up, when i try to enter the mapping-table.
I found out, that the difference between entering the mapping-table before and after a data-transfer is the use of the auto-mapping-feature.
The auto-mapping automatically inserts some mapping-entries into the mapping-table during (or right before) the transfer-process.
You can see this, if you enter the mapping-table before the data-transfer, leave it empty, run the data-transfer and reenter the mapping-table after the data-transfer. Now there are entries for each auto-mapping-option.
So, i guess, there is something in the auto-mapping-process, which causes the error.

**Comment by bcolpaert** [comment] 2018-08-03 07:55
Hi,

I could reproduce this issue and the mapping list bug should be resolved in v1.2018.8.1

Can you confirm this?

BR, 
Bram

**Comment by duck-o-saurus** [comment] 2018-08-06 12:15
Hi Bram,

i can confirm, that the new release resolved the issue.
Thanks a lot!

Best greetings :)

**Closed** 2018-08-08 05:39 UTC
Labels: bug
